#!/usr/bin/ruby
require 'rubygems'
require '~/projects/cpee-testing-framework/fulltest'

options = {
  :host => 'localhost',
  :port => 9303,
  :secure => false
}

Riddl::Server.new(CPEE::InstanceTesting::SERVER, options) do
  
  if File.exist?('events.db')
    File.delete('events.db')
  end

  # TODO: understand these features
  accessible_description true
  
  cross_site_xhr true
  
  
  puts "Hello from testing server"
  
  
  # local CPEE
  @riddl_opts[:cpee] ||= 'http://localhost:8298/'

  use CPEE::InstanceTesting::implementation(@riddl_opts)
end.loop!

#at_exit {File.delete("events.db")}